### ISSUE TITLE
How to make floating action button transform into full screen form

### ISSUE THREAD

**Issue by dineshmm23** [BrotherV/Floating-ArcMenu#21]
In my application I have a FAB and I want to use it to create items. The animation I want to achieve is the one labelled under "Full Screen" in the material designs guidelines `https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions`

Does know how I can achieve this?

**Comment by BrotherV** [comment]
Android original FAB does not relate to this library. this library has its own floating action button.
