### ISSUE TITLE
Close menu from code

### ISSUE THREAD

**Issue by avalenzuelac** [BrotherV/Floating-ArcMenu#3]
Hi bro!
I appreciate so much your help.. How can I close the menu from the code?

Thanks!

**Comment by BrotherV** [comment]
Hi my friend, if you want to close menu programmaticaly just use performClick() method. It will close the menu If it's open.

**Comment by avalenzuelac** [comment]
`if (menu.isEnabled()){
            menu.performClick();
        }`

This was what I needed, Thanks bro!
